[tool.poetry]
name = "hanziart"
version = "0.1.0"
description = ""
authors = ["greggelong <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^8.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
